### ISSUE TITLE
The scores on the test set

### ISSUE THREAD

**Issue by tuyunbin** [jayleicn/TVCaption#1]
Hi Jie,

I have a question that when using the baseline code, I got the results on the val set as follows:
{
    "CIDEr": 44.60104356673421,
    "Bleu_4": 10.51846039469163,
    "Bleu_3": 16.774655841521515,
    "Bleu_2": 28.011344598729583,
    "Bleu_1": 50.9832024307741,
    "ROUGE_L": 32.188248212703236,
    "METEOR": 16.4603744520034
}, which are also equal to the results in ''standalone_eval/sample_val_predictions_metrics_raw.json" you provided in the code. However, in your paper, the results on the val set are 10.53 16.61 32.35 44.39, so I wanna know when using your baseline code, are the results on the test set equal to the results reported in the paper?

**Comment by jayleicn** [comment]
Hi @tuyunbin,

Since the baseline code has been cleaned for release, it could not output the original exact results even using the same random seed. But the performance is close enough to be reproducible. As the `val` results are slightly different from the paper, the `test-public` results will also be different.

Jie

**Comment by tuyunbin** [comment]
Hi Jie,

Since I'm gonna write a paper recently, I wanna know the baseline results in the test set using your released code. I found the results in https://competitions.codalab.org/competitions/23109#results are 10.77 (2) | 16.72 (2) | 32.67 (2) | 45.05 (2), which are slightly different from the results in your paper. So, do you get these scores by using the model trained via this released code?

**Comment by jayleicn** [comment]
Yes, it is only used for testing the submission platform. Please use the results in our paper if you are making a comparison in a paper. Sorry for the confusion.

**Comment by tuyunbin** [comment]
Thank you for your kindly help.
